const mongoose = require("mongoose");

//Define a schema
const Schema = mongoose.Schema;
const SepSchema = new Schema({
  noSep: {
    type: String,
    required: false,
    default: null,
  },
  noKartu: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  tglSep: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  ppkPelayanan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  jnsPelayanan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  klsRawatHak: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  klsRawatNaik: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  pembiayaan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  penanggungJawab: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  noMR: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  asalRujukan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  tglRujukan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  noRujukan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  ppkRujukan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  catatan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  diagAwal: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  tujuan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  eksekutif: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  cob: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  katarak: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  lakaLantas: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  noLP: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  tglKejadian: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  keterangan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  suplesi: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  noSepSuplesi: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  kdPropinsi: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  kdKabupaten: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  kdKecamatan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  tujuanKunj: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  flagProcedure: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  kdPenunjang: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  assesmentPel: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  noSurat: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  kodeDPJP: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  dpjpLayan: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  noTelp: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
  user: {
    type: String,
    trim: true,
    required: false,
    default: null,
  },
});
module.exports = mongoose.model("Sep", SepSchema);
